### ISSUE TITLE
Audio fails after wake from sleep

### ISSUE THREAD

**Issue by jbrodriguez** [theracermaster/Gigabyte-GA-Z77X-macOS-Install#21]
Hi @theracermaster, I installed el capitan using this guide and it's working beautifully.

Up until now, I could never get sleep to work.

Thanks for your efforts on this project.

The only issue I've run into is that audio works for a while after waking from sleep, then fails (no sound).

I can get it to work again by switching outputs, from digital out to internal speakers and viceversa, but after a little while it fails again.

I found this workaround, https://github.com/cliffom/appleHDAReset, which unloads/reloads AppleHDA.kext, then restarts CoreAudio.

I will be testing it and report back.

In any case, my log shows this
11/2/15 08:36:53.000 kernel[0]: Sound assertion in AppleHDAFunctionGroup at line 1058

These are the audio in/out devices I have
![image](https://cloud.githubusercontent.com/assets/1305422/10883028/41383c2c-813d-11e5-8553-cc37bd9e85e9.png)

These are the machine's specs
Mobo: Gigabyte GA-Z77X-UD5H
CPU: intel core i5-3570k
Graphics: gigabyte geforce gtx 660ti

**Comment by theracermaster** [comment]
Will test and see if I can reproduce this. In the meanwhile, you can try using [CodecCommander](https://github.com/Dolnor/EAPD-Codec-Commander). Note that this will need to be installed to /Library/Extensions (Clover EFI kext injection won't work).

**Comment by CoBrA2168** [comment]
FYI - noticed I had the same problem with switching from "Internal Speakers" to "Headphones."  Installing CodecCommander seemed to fix the problem.

**Comment by CoBrA2168** [comment]
Sorry to revive an old issue, but I appear to be having a similar issue as to the OP of this thread, but only about 25% of the time or so.  And only when I'm using Digital Out as my audio source.  Also on El Capitan 10.11.6

This person here seems to have the same exact issue and solved it by modifying the DSM method:
http://www.insanelymac.com/forum/topic/310828-alc1150-external-amplifier-and-sleep-issues/

The only difference between Toleda's DSM method and yours was the "PinConfigurations" missing from yours, so I added that just now.  I'll wait and see if it proves to help.

**Comment by theracermaster** [comment]
With AppleALC, what additional changes do you need (CodecCommander/etc) do you need for audio to fully work after sleep? I'm in the process of updating the repo. My headphone jack audio works fine after sleep, but I haven't tested Line Out/Digital. Layout ID 3 is used for HD 4000 HDMI audio (it doesn't work with toleda's layout ID 1).

**Comment by CoBrA2168** [comment]
Yes, you are correct about the Layout ID which I did not realize when I made my changes last week.

My current audio setup is as follows:

- Remove the AppleHDA898 kext from /L/E
- Download AppleALC.kext (and Lilu.kext) from https://github.com/vit9696/AppleALC/releases
- CodecCommander.kext installed with the Custom Commands mentioned above (not sure if this is necessary anymore)
- HDEF as follows (I'm going to use Layout Id 1 since I don't use the Intel Graphics:
`Method (HDEF._DSM, 4, NotSerialized)  // _DSM: Device-Specific Method
        {
            If (LEqual (Arg2, Zero))
            {
                Return (Buffer (One)
                {
                     0x03                                           
                })
            }

            Return (Package (0x06)
            {
                "layout-id", 
                Buffer (0x04)
                {
                     0x01, 0x00, 0x00, 0x00                         
                }, 

                "hda-gfx", 
                Buffer (0x0A)
                {
                    "onboard-1"
                }, 

                "PinConfigurations", 
                Buffer (Zero) {}
            })
        }`
- `Device (HDAU)
            {
                Name (_ADR, One)  // _ADR: Address
                Method (_DSM, 4, NotSerialized)  // _DSM: Device-Specific Method
                {
                    If (LEqual (Arg2, Zero))
                    {
                        Return (Buffer (One)
                        {
                             0x03                                           
                        })
                    }

                    If (LNotEqual (^^GFX0.VID0, 0x8086))
                    {
                        Return (Package (0x04)
                        {
                            "layout-id", 
                            Buffer (0x04)
                            {
                                 0x01, 0x00, 0x00, 0x00                         
                            }, 

                            "hda-gfx", 
                            Buffer (0x0A)
                            {
                                "onboard-2"
                            }
                        })
                    }
                    Else
                    {
                        Return (Package (0x01)
                        {
                            Zero
                        })
                    }
                }
            }
        }`
- IGPU DSM is using this block in your If/else code:
`Return (Package (0x06)
                    {
                        "AAPL,ig-platform-id", 
                        Buffer (0x04)
                        {
                             0x07, 0x00, 0x62, 0x01                         
                        }, 

                        "device-id", 
                        Buffer (0x04)
                        {
                             0x66, 0x01, 0x00, 0x00                         
                        }, 

                        "hda-gfx", 
                        Buffer (0x0A)
                        {
                            "onboard-1"
                        }
                    })`
- GFX0 DSM:
`Return (Package (0x0E)
                        {
                            "@0,connector-type", 
                            Buffer (0x04)
                            {
                                 0x00, 0x08, 0x00, 0x00                         
                            }, 

                            "@1,connector-type", 
                            Buffer (0x04)
                            {
                                 0x00, 0x08, 0x00, 0x00                         
                            }, 

                            "@2,connector-type", 
                            Buffer (0x04)
                            {
                                 0x00, 0x08, 0x00, 0x00                         
                            }, 

                            "@3,connector-type", 
                            Buffer (0x04)
                            {
                                 0x00, 0x08, 0x00, 0x00                         
                            }, 

                            "@4,connector-type", 
                            Buffer (0x04)
                            {
                                 0x00, 0x08, 0x00, 0x00                         
                            }, 

                            "@5,connector-type", 
                            Buffer (0x04)
                            {
                                 0x00, 0x08, 0x00, 0x00                         
                            }, 

                            "hda-gfx", 
                            Buffer (0x0A)
                            {
                                "onboard-2"
                            }
                        })`

With these changes, my audio appears to work fine after sleep (and switching from Digital to Line out does not "break" the audio like it did before).  Also, I can confirm HDMI audio working correctly with my Nvidia Graphics card.  I can't verify Intel would work if I used Layout ID3 though.  For me, this is fine.

As a reminder, here are my computer specs:
- Z77x-UD5H v1.1
- i7-3700 (non-K, HD4000 graphics for this card)
- Discrete graphics GTX670 with stock drivers (non-web)
- El Cap 10.11.6

Hopefully this help!

**Comment by theracermaster** [comment]
I pushed v2.0.0, which now uses AppleALC. Please test and see if audio fully works after wake (without CodecCommander).

**Comment by CoBrA2168** [comment]
@theracermaster - sounds good, still running El Capitan at the moment, I need to get a spare SSD for Sierra.

However, I can comment on some more audio things. I noticed that every once in a while, my HDMI audio does not show up on boot when using AppleALC. But the digital audio cutouts do not occur with this kext. I switched back to Piker-alpha method (and tried another method by Toleda) with the same side effects as before. But the HDMI audio always showed up. So it's one problem or another. I don't actually use my HDMI audio right now, so AppleALC it is. I'd be curious to hear if anyone else has issues with HDMI audio using your new update.

**Comment by theracermaster** [comment]
Can't say that I've had the same issue - I've been exclusively using HDMI audio for a few months now without any issues. It could've been an issue with the old SSDTs, but I'm not really sure.

**Comment by CoBrA2168** [comment]
Yeah, I'm not sure either.  It's probably something weird with my setup since I've made a few changes to it since I used your script.

I don't know how soon I can get to using the script, but when I do, I'll be sure to report back my successes or failures.  Maybe @jbrodriguez could try to use your latest script to see if it fixes his audio issues (since I sort of hijacked this issue all together).

**Comment by jbrodriguez** [comment]
So, what I did (Apr last year) was to purchase a usb digital audio adapter (Turtle Beach Audio Advantage Micro II USB Analog & Digital Audio Adapter) and never looked back :)

It shows up as USB Sound Device in my input/output devices. I can switch to/from Internal Speakers, use Soundflower to multi route, etc. it works really fine.

**Comment by CoBrA2168** [comment]
@jbrodriguez you should consider trying the AppleALC kext (or just using @theracermaster's new script) since it solved the very same issue that you were experiencing on my board.

**Comment by jbrodriguez** [comment]
Ok, didn't know that.

I'm currently on Sierra, and will upgrade soon to 10.12.4, which just came out. I'll try the new script after that.

I'll open an issue about clover boot timeout though.

In the previous version, the timeout wasn't enabled (at least not for me). Not such a big deal, but it comes in handy.

Not sure if v2.0.0 has the timeout or not.

**Comment by CoBrA2168** [comment]
@jbrodriguez FYI, you can configure the timeout from within the Clover config.plist.  See https://clover-wiki.zetam.org/Configuration/Boot#Timeout

**Comment by jbrodriguez** [comment]
Thanks @CoBrA2168 ! I'll look into it.

**Comment by theracermaster** [comment]
Front panel audio seems to work fine after sleep since v2.0.0. I do not use the additional ports on the back of the motherboard, so please feel free to reopen this issue if those ports do not work after sleep.
