### ISSUE TITLE
Z97 Support

### ISSUE THREAD

**Issue by chroniX0** [theracermaster/Gigabyte-GA-Z77X-macOS-Install#22]
I was wondering if there are any plans to extend support to the Z97 platform? I love your patch for my Ivy Bridge setup, but am upgrading to Haswell soon (i7-4790k + Z97X-UD5H), just waiting on the parts to arrive. It would be great to see support for this added if it's not too much trouble. I'd be happy to provide DSDTs, IOReg dumps or any other pertinent data when I get all the parts if it would help any. Either way, thanks for all your hard work!

**P.S.** Do you know how feasible would it be to migrate my existing El Capitan installation (that's using files generated for the Z77X-UD5H with your patch) to the Z97X-UD5H?

**Comment by theracermaster** [comment]
I have no Z97 hardware, but if you are willing to spend a few days testing things with me I guess it should be possible. I don't have much free time during the week, so it would have to be during the weekend, but I will definitely consider this.

**Comment by chroniX0** [comment]
Sorry for the late reply -- I'd definitely be willing to test things out and experiment! :+1:

Thanks for the guideline too, the last part I'm waiting on (PSU) should be coming in today so I can finally get this built. I'll be upgrading the bios to the [latest F10 version](http://www.gigabyte.com/products/product-page.aspx?pid=5360#bios) first and proceed from there. I'm assuming you'll need the DSDT and an IOReg dump so I'll be sure to send those once I'm up and running. If there's anything else, please let me know -- thanks!

**Comment by chroniX0** [comment]
Hope you had a good Thanksgiving week! I finally got everything up and running, and had to use a Unibeast USB just as a way to boot into my existing installation. Once I was in, I removed the AppleHDA898 and FVInjector kexts.

Here's the DSDT, IOReg dump & acpi/origin folder: https://transfer.sh/1VBAD/z97x-ud5h.zip

I also found a DSDT patch for this motherboard (Z97X-UD5H). I went ahead and patched it and uploaded here in case it could be useful: https://transfer.sh/10xPz5/dsdt-patched.aml

Once again thanks for taking the time to help me, I really appreciate it! :smiley:

**Comment by theracermaster** [comment]
Thanks, will take a look at this and will probably get something up (new repo) soon, after I update this repo.

**Comment by chroniX0** [comment]
So, I have some updates that may be helpful. Basically, I tried to recreate your work as best I could and managed to get a working install. I've laid out the steps taken below: 

First, I installed the latest Clover to the EFI partition and removed a bunch of unnecessary components (like 32-bit boot files/drivers, docs, etc.) to keep the installation minimal like yours. 

Next, since I didn't know how nor which fixes to apply for my motherboard, I resorted to a ready-made solution which patches the DSDT with the appropriate fixes instead of your cleaner, simpler method of incorporating the necessary fixes within the config.plist file. Using MaciASL, I patched the DSDT with [pjalm's edits](http://pjalm.com/repos/gigabyte/) that are designed for this motherboard. I also applied his USB edits which basically renames XHC1 to XHC, EHC1 to EH01, etc. so as to not conflict with Apple's USB injection methods.

Then, using Piker-alpha's ssdtPRGen, I was able to generate an SSDT.aml that matches my processor and appropriate SMBIOS (iMac 14,2). I used the option -Turbo 4700 to account for my overclock which is currently at 4.7GHz. I came to realize that, in addition to the standard SSDT.aml, an SSDT-1.aml was needed for these Haswell-refresh CPUs. (I ended up putting all the various SSDTs that were generated by ssdtPRGen inside the ACPI/patched folder just in case, though that's probably excessive and unneeded.)

Afterwards, I placed all the necessary kexts that I knew of, some old (from my prior install that used your repo), some new. For audio, I used toleda's cloverALC patch for the Realtek ALC1150 chipset. For USB port injection, I used RehabMan's FakePCIID.kext (and his XHCIMux.kext, which I placed within FakePCIID).

Finally, I configured Clover's config.plist file. One thing I came to learn that was different for the 4790k versus the 3770k is that I have to drop certain SSDT tables (Cpu0IST & CpuPm) to enable proper power management states. Other than that, it's virtually the same as the config.plist from your repo. Well, besides your DSDT fixes of course.

Last thing to note is that while on paper, iMac 15,1 appears to be the ideal SMBIOS that best matches the CPU I have (i7-4790K) -- it requires some more legwork and involves [editing AppleGraphicsControl.kext](http://www.tonymacx86.com/graphics/161439-gtx-970-black-screen-after-nvidia-346-01-02f01-2.html#post1018395) to get it working properly. iMac 14,2 has no such issues so I used that instead.

Overall, my system seems to be working fine with only this cosmetic issue (Generic AHCI Controller):
![Generic AHCI](http://i.imgur.com/aSEiMIV.png)

Here's a [zip of the working EFI folder](https://transfer.sh/13sBKC/efi.zip) and an [IOReg dump](https://transfer.sh/14njFL/imac.ioreg.zip). Hopefully it can be of some help to you for adding support for the Z97 platform. Just wanted to thank you again for your time and all your help.
