### ISSUE TITLE
HDMI Audio Woes (and other GPU-related issues)

### ISSUE THREAD

**Issue by CoBrA2168** [theracermaster/Gigabyte-GA-Z77X-macOS-Install#23]
TheRacerMaster,

First off I want to say thank you for all the hard work you've put into this tool.  It's been very helpful.

Here's my complete specs:
GA-Z77X-UD5H rev 1.1, BIOS F16g (from a member on insanelymac, has patches for firewire)
Core i7-3770 (non-k version)
Nvidia GTX 670
32GB RAM
OSX El Capitan 10.11.1

I recently sent you a few messages over reddit about installation issues.  Luckily, I've gotten past all of those.  They were all related to my graphics (internal vs discrete) or BIOS versions.  My winning combination was to unplug all DVI cables / HDMI cables, use Internal graphics for "init display first," and plug in the DVI port.  I needed CSM support to be set to "Always" too, for some reason (my GPU supports UEFI, or at least it should).  I also got a BIOS from a member on insanelymac that works great.  Finally, I was able to install without any issues and get to the El Capitan main screen.  I installed the post-install script without any issues.  I have init display first back to PEG, but I have IGPU Enabled still (as per the instructions).

Under first impressions, everything seems to be working perfectly.  EXCEPT one thing.  My HDMI audio is not working.  My HDMI audio I use is from my discrete graphics card (the GTX 670).  I also use the other 2 DVI ports for a total of 3 displays.

With Yosemite and a custom DSDT, I was able to get this to work without any issues.  I remember it had something to do with picking the correct layout-id, but I'm having trouble remembering.

Any ideas on what I should do here?

Thanks!

**Comment by CoBrA2168** [comment]
Okay, so I fixed the HDMI audio.  I was able to fix it by replacing your DSM method for GFX0 in the SSDT with the following:
```
Return (Package (0x0E)
                        {
                            "AAPL,slot-name", 
                            "Slot-1", 
                            "name", 
                            "Display Controller", 
                            "@0,connector-type", 
                            Buffer (0x04)
                            {
                                 0x00, 0x08, 0x00, 0x00
                            }, 

                            "@1,connector-type", 
                            Buffer (0x04)
                            {
                                 0x00, 0x08, 0x00, 0x00
                            }, 

                            "@2,connector-type", 
                            Buffer (0x04)
                            {
                                 0x00, 0x08, 0x00, 0x00
                            }, 

                            "@3,connector-type", 
                            Buffer (0x04)
                            {
                                 0x00, 0x08, 0x00, 0x00
                            }, 

                            "hda-gfx", 
                            Buffer (0x0A)
                            {
                                "onboard-2"
                            }
                        })
```

I also changed onboard-1 to onboard-2 in the HDAU below.  Now my HDMI audio works as before from the discrete graphics card.

BUT I'm still having other issues.  I'm having all sorts of issues related to graphics and USB.  For one, if I boot with my Logitech USB Camera in, everything goes haywire.  When this happens, I boot to a black screen.  To get booting again, I literally have to REFLASH the BIOS.  Otherwise, I can never get back to booting.

I also notice that sometimes my boot will be very slow (30-40) seconds.  It seems be getting hung up on something with the IGPU
```
timed out waiting for IOKit to quiesce
```

Any ideas about these other issues?

**Comment by theracermaster** [comment]
Hi, sorry for not responding earlier (was busy with class). Your issues are very odd, I've never seen these before. Are you running the recommended UEFI settings in the wiki? Can you post another IOReg dump (once your install finishes)? [Here's](https://transfer.sh/68QuG/z77x-ud5h.rom) my personal modded UEFI (use at your own risk).

**Comment by CoBrA2168** [comment]
Sorry it took me so long to respond.  I was gone for the Thanksgiving break.

Anyway, I finally got my install working using your script.  After about 2 days of banging my head against the wall, I resorted to using my old config.plist file from Yosemite to see what could have possibly changed.

Stupid me finally figured it out after hours of troubleshooting.  I have a 3770 processor (non-K) model.  This is important since it supports Vt-d which doesn't play nicely with Clover and hackintosh machines.  This was causing all sorts of issues, including corrupting my BIOS from time to time.  It was giving me random black screens and issues booting into OSX.

The solution is simple: if you have a CPU that supports Vt-d, it either needs to be disabled in the BIOS or a table needs to be dropped from the DSDT.  I chose to drop the table from the DSDT using a Clover patch (see here: http://www.insanelymac.com/forum/topic/284656-clover-general-discussion/page-431#entry2178271).

I can't believe this ended up being my problem.  After I dropped the correct table, all of my problems went away.

Oh but I still needed to modify the SSDT to get HDMI audio working with my GTX 670 (see above).

Thanks for all of your hard work!

**Comment by theracermaster** [comment]
Thanks for the issue report, I will add DMAR table dropping to the config.plist in the repo in the next update.

**Comment by CoBrA2168** [comment]
Yep.  I would just check to see if the CPU supports Vt-d (all of the non-K models) and add the dropping of the table if it does.  Actually, you might be OK dropping the table for all CPUs but I'm not 100% sure on that.

Once that was fixed, everything worked fantastic.  This script is super handy and I hope you keep it updated for the next version of OSX!
