### ISSUE TITLE
Stuck at installer first boot, Beachball on Blackscreen/Apple logo

### ISSUE THREAD

**Issue by Bobbm** [theracermaster/Gigabyte-GA-Z77X-macOS-Install#25]
Z77X UD3H, BIOS version FA, no external GFX, monitor on HDMI port, USB k/b&mouse, one SSD, one HDD.

Using your EFI, but with El Capitan (10.11.3) installer on USB flash, I can boot to Clover Ok, and get through initial Installer boot up until the black screen with Apple logo, then nothing on progress bar and after a few seconds, beachballl appears, and no more progress. 

I have tried a variety of different USB port combinations to plug in my Installation USB and k/b-mouse, and have tried multiple USB flashdrives. Have also checked and double checked my BIOS settings, but of course, there are a few minor differences between my BIOS and the one in your instructions, so a few settings not sure what is best, though I started with defaults. 

I had a working Yosemite/Clover hack on this board, but this had lots of non-working USB ports, so decided to move to a clean install of ElCap. In the process I managed to muck up the previous EFI, so now nothing boots. fortunately I do have a MBP I can create boot USBs on. If need be I could make edits to your EFI via my MBP.

Any suggestions? Would it help if I post photos of the boot prior to Apple Logo?

Thanks

**Comment by theracermaster** [comment]
Do you see FakeSMC loading if you try verbose boot? You might want to try booting without caches.

**Comment by Bobbm** [comment]
SMC is loading ok. Booting without caches still results in a panic when booting the installer.

Wonder what your best guess is: is this something that can be solved in BIOS settings, or boot options when booting installer, or in clover/config.plist?

FWIW, here are some shots of the installer boot before the apple logo. Apologies for quality, I haven't got everything because it whizzes by so fast.


![img_0074](https://cloud.githubusercontent.com/assets/16848980/12541759/ed3ce1e4-c355-11e5-9b51-e726d6bb2091.jpg)
![img_0075](https://cloud.githubusercontent.com/assets/16848980/12541761/ed8998d6-c355-11e5-9473-ded88245285a.jpg)
![img_0076](https://cloud.githubusercontent.com/assets/16848980/12541763/ed8da9e4-c355-11e5-93b6-6e1ea83e5275.jpg)
![img_0077](https://cloud.githubusercontent.com/assets/16848980/12541764/ed8eefa2-c355-11e5-9d0b-987cfc8bd749.jpg)
![img_0078](https://cloud.githubusercontent.com/assets/16848980/12541762/ed8da052-c355-11e5-87c2-586500e382ed.jpg)

**Comment by theracermaster** [comment]
What does the panic say when you try booting without caches?

**Comment by Bobbm** [comment]
Not sure if panic is the right term here, but anyway, booting with/without caches is the same end result. The screen photos posted abov were of an attempted boot without caches. 

Either way, it gets all the way to the Apple logo on the first boot of installer, then it continues to access stuff on USB for a bit (my flash device has an activity light) then sits for a minute or so, tho nothing shows on progress bar, then I get the beachballl and it's end of story.

Four ideas/questions:

1) is there a way to get Clover to force the OSX installer boot process to log all messages to somewhere on the EFI, including those after the apple logo is up, so I can view them on the USB on another machine to see what's going wrong at the point of freeze? (Messages zip by on the screen pretty fast, then of course there are no messages displayed after logo appears, even though freeze up is 10-20 seconds later.)

2) could my problem simply be an ElCap incompatibility, or has your install/post-install clover+tool suite already been working for 10.11 already? Maybe I should use your method with Yosetmite, then try to upgrade some other way. 

3) are there some other boot options I can invoke from clover which might help get the installer booted? safe mode or something?

4) finally, if instead I am able to get a rough working 10.11 install using some other, more generic method and config.plist initially, will your gigabyte-specific post install scripts still do their magic to tweak to fit my motherboard? Or do your scripts depend on certain settings/kexts being setup just right in the initial install procedure?

Thanks so much for any advice.

**Comment by Bobbm** [comment]
Just to update, I have got this working, though not exactly sure what I did to resolve the problem. 

Unable to find the cause of my problem with your guide,  I first tried unsuccessfully to follow another El Cap/Clover install guide, and that guide curiously advised using two USB flash drives, one with Clover and a separate one with the El Cap installer (10.11.3). Although that didn't work with the clover settings recommended there, just as a shot in the dark I tried copying your EFI, complete with your config.plist, onto the dedicated clover USB. that booted ok to Clover, then I was able to get the OS X installer on the other USB to boot and run. Thereafter, your post-install scripts all ran fine.

Thus I can't be sure whether it was using separate USBs which made the difference, or what. It's possible that I ended up with some small but critical difference in BIOS settings, but I didn't keep that close track of all that, so can't be sure.

anyway El Cap is installed and booting OK and audio, network, sleep, iCloud login and most other things all work. Trim seems not working, but that shouldn't be hard to solve. 

Main problem now seems to be USB, only a few of the ports are working at all, haven't yet investigated what is 2.0, what is 3.0, and haven't yet tried any fixes, still researching. Any suggestions here?

Overall, that's for a good toolset.

**Comment by theracermaster** [comment]
Is your XHCI mode set to Enabled in your BIOS? Can you post an IOReg dump as well?

**Comment by Bobbm** [comment]
XHCI Mode in BIOS is set to Auto. If I set it to Enable any keystroke at all from my USB kbd will instantly crash application.

These are the USB symptoms:
1) Working USB ports: two front panel ports (jumpered to motherboard), two back panel ports adjacent to the nth port. Other four back panel USB ports do not work at all. (recall I am on a Z77X UD3H)

2) All working USB ports are erratic. My USB keyboard works fine in BIOS and Clover, but often needs to be plugged in again after OS X boot to be seen. Wireless mouse is same problem, because its transceiver is plugged into keyboard thru port.

Here is an IOJones dump: 
[MH’s iMac.iojones.zip](https://github.com/theracermaster/Gigabyte-GA-Z77X-DSDT-Patch/files/122686/MH.s.iMac.iojones.zip)
