### ISSUE TITLE
USB 3.0 Speeds

### ISSUE THREAD

**Issue by colin-marshall** [theracermaster/Gigabyte-GA-Z77X-macOS-Install#27]
Hello, first off, thanks for your work on this. I apologize in advance for the length of this post.

Before coming across this repo, I followed other guides to get 10.11 working on my setup. iMessage, App store, audio, graphics, etc. are all working. The one thing that was not working was the USB 3 ports were only giving USB 2 speeds, and a couple ports on F_USB_1 were not working due to the 15 port max.

I took `FakePCIID.kext` and `GA-Z77X_USB.kext` from this repo and put them in the `10.11` directory of my Clover bootloader. After doing this, the ports that were not working are now operational! All USB 3 ports are still only giving me USB 2 speeds though, so that's the only thing left to fix.

**Here are my questions:**
1. Is there something special that your installer does that would get USB 3 speeds working? I am thinking something possibly related to power management or DSDT? The guides I used did not have me do anything in either of those departments.
2. Are there any diagnostic tools I can use to help me find the source of the problem?
3. Could BIOS be the source of the problem? I have not tried different bios because I didn't want to mess anything up since almost everything is working great. 
4. Do you have any recommendations? I have a plan of action to see if I can get USB 3 speeds working, any insight to what I have below would be greatly appreciated.

Here are my specs:
- UD5H rev1.1 (F15O BIOS)
- i5 3570k
- GTX 650 Ti
- Samsung 850 500gb SSD
- Focusrite Firewire sound card (important that firewire always works, although I have onboard audio working too)

I currently have 2 drives that I use as clones/backups of my El Capitan SSD boot drive and I don't mind testing different stuff on one those drives. In order, these are the steps I have thought of trying:
- **Plan 1**
  - Remove clover off the clone drive that I'm testing on
  - Follow Gigabyte-GA-Z77X-DSDT-Patch installation instructions for that drive/install
  - Test USB ports & speeds
- **Plan 2**
  - Take a different spare drive and do a fresh install of El Capitan on it
  - Follow Gigabyte-GA-Z77X-DSDT-Patch installation instructions for that drive
  - Test USB ports & speeds
- **Plan 3**
  - Change bios to F14
  - Test USB ports & speeds on working install, clone/test install, and new/clean install
- **Plan 4**
  - Change bios to F16 mod
  - Test USB ports & speeds on working install, clone/test install, and new/clean install

Thanks!!!

**Comment by colin-marshall** [comment]
@theracermaster since my post the other day, I came across this post of yours on reddit:
https://www.reddit.com/r/hackintosh/comments/3hdl0f/update_gigabyte_gaz77x_post_installation_script/cvpad2w

I've done everything in that post now, still getting USB 2.0 speeds. Here is an ioreg dump:
https://www.dropbox.com/s/h8q6w8a11awr525/ioregdump.ioreg?dl=0

If you could take a look it would be very appreciated. Thanks!

**Comment by theracermaster** [comment]
Hi, sorry for not responding earlier. According to your IOReg, the USB 3 devices *are* connecting to the xHCI device (USB 3.0) which is good. What does System Information > USB show? Also, try setting the xHCI mode in your BIOS to Enabled (instead of Auto or Smart Auto).

**Comment by colin-marshall** [comment]
@theracermaster thanks for the quick response! Below is my sys info, if you need to see other parts of it let me know. Everything looks normal to me. I have tried the different xHCI modes and didn't notice a difference, but I will try again.

![screenshot 2016-04-03 14 21 58](https://cloud.githubusercontent.com/assets/4453733/14255486/75ee4140-fa51-11e5-9289-2db741da9892.png)

I forgot to mention that I can actually get one of my USB 3.0 flash drives to do 110MB/s read, which I believe is almost double USB 2.0 speed, but I can't get it to write over ~25MB/s. Other reviews from users of the same flash drive show way higher write speed, so unless my specific flash drive has issues, there is still something not working properly.

I have a Macbook Pro but it is older and doesn't have USB 3 ports so I am going to borrow a friend's laptop with USB 3 ports and run some tests on my USB 3 flash drives to make sure they are not the problem.

One last thing of note: I use virtualbox and vmware for development and they both have USB kexts for use of the USB ports on a virtual machine. I'm curious if they could be causing the speed issues. I have no VM's running when I test the USB speed though. I may try to remove those kexts temporarily to see if it makes a difference.

**Comment by theracermaster** [comment]
*Should* be fixed in v2.0.0, feel free to reopen if you encounter any new issues.
