### ISSUE TITLE
Z77M-DH3 Support

### ISSUE THREAD

**Issue by agustinlacorazza** [theracermaster/Gigabyte-GA-Z77X-macOS-Install#32]
Hi,

Your are doing an awesome work, im wondering if you please could add the support to the model Z77M-DH3 

Attach the reg

[IORegistryExplorer.zip](https://github.com/theracermaster/Gigabyte-GA-Z77X-DSDT-Patch/files/429303/IORegistryExplorer.zip)

Thanks
Regards

**Comment by theracermaster** [comment]
Hi,

Adding support for the GA-Z77M-D3H doesn't seem difficult, but I need an IOReg dump. The attached ZIP is just a copy of IORegistryExplorer.

**Comment by agustinlacorazza** [comment]
Hi, 

lol, im just rookie in this world, linux fan, look at this and check if it okay please,

Attached again
[agustin.ioreg.txt](https://github.com/theracermaster/Gigabyte-GA-Z77X-DSDT-Patch/files/431320/agustin.ioreg.txt)

**Comment by theracermaster** [comment]
Do File>Save As in IORegistryExplorer, or `ioreg -lw0 > ioreg.txt` in Terminal.

**Comment by agustinlacorazza** [comment]
Okay, think that i send you the device tree, sorry.. this is ioreg
[ioreg.txt](https://github.com/theracermaster/Gigabyte-GA-Z77X-DSDT-Patch/files/431347/ioreg.txt)

**Comment by VasiliyLuch** [comment]
[ioreg.txt](https://github.com/theracermaster/Gigabyte-GA-Z77X-DSDT-Patch/files/831944/ioreg.txt)
Will it helps you? I'm now running on Z77M-D3H.

**Comment by theracermaster** [comment]
Support has been added in v2.0.2. Reopen if there are motherboard-specific issues.
