### ISSUE TITLE
Will this work for Sierra?

### ISSUE THREAD

**Issue by Bobbm** [theracermaster/Gigabyte-GA-Z77X-macOS-Install#34]
I had good success installing Yosemite with this patch, then later did a direct App Store upgrade to ElCap which worked mostly - some USB misbehavior which I chose to live with rather than try to sort out. I understand this was probably due to changes to USB stack in 10.11.

I recently attempted direct upgrade to Sierra, which only sorta worked, and led me into a day or two of trying to get back up the Hackintosh learning curve and get it sorted. In the end, I decided to try Uni/Multibeast, figuring they have been doing clover-based hacks long enough by now. This install mostly works, after a little fiddling and switching a kext or two. But i  still have USB problems. Some ports work, some not so much. (I don't even know if audio works, 'cause i use an outboard USB audio (Roland).)

Current problem with USB, aside from one or two ports not reliable, is that even ports that work for USB flash I/O don't work properly for USB MIDI. Googling, I haven't yet found anything that suggests kext problems which would directly affect MIDI, so I would like to first get USB sorted out (useful for its own sake), then see if that also resolves MIDI issues.

do you think I can get USB working by just replacing any USB kexts with GA-Z77X_USB, FakePCIID and FakePCIID_XHCIMux,  and adding to config.plist DSDT patches for EHC1/EHC2 to EH01/EH02 and XHC to XH01, or alternatively, will a clean install of Sierra using this method and Z77X script tool work?

I have:
Z77X-UD3H
i7, internal GFX only

thanks

**Comment by ch0w7** [comment]
would also like to see this working as my audio devices are not found again.

**Comment by theracermaster** [comment]
Try the [sierra branch](https://github.com/theracermaster/Gigabyte-GA-Z77X-DSDT-Patch/tree/sierra). I made some changes (such as removing the USB injector), and would like testers.

**Comment by Bobbm** [comment]
Thanks for doing this update; very happy to give this a test. But first one key question: 

Do i need to 1) do a clean Sierra/Clover install using your install config first, or can i 2) start from my existing, partly working Sierra/Clover install, and simply clone into your git repository, cd, then run the script? 

If the latter, any minor precautions or modifications I should make first? My current Sierra install was done with Uni-/Multibeast, followed by a few kext substitutions and a few minor changes to config.plist. Looks like your script will replace existing config with yours, correct?

Also, do you know if I will need to check whether Multibeast has left anything in S/L/E which might conflict your your approach, or if I need clean anything out of /EFI/CLOVER/kexts/Other before running your script? 

Thanks

**Comment by mickelsn** [comment]
I used the prior version of this script for El Capitan. Based on that experience, I highly suggest using a second SSD or similar drive and doing a clean install and getting things working - especially since this is an early test version of the script. The maintainer was great in responding to and fixing some bugs I ran into previously, helping me getting a working stable install.

Also, using a separate boot drive and doing a clean install ensures that any issues you run into aren't due to external factors such as the HniBeast/Multibeast install's peculiarities.

Once you have a working install, you should be able to copy the various serial numbers and whatnot from your current working setup to the new one to successfully log into iMessage and whatnot - or generate clean ones that match the new system type if needed.

**Comment by Bobbm** [comment]
I spent sometime today trying to test out the Sierra branch of this patching script, but could not get a first install of sierra using the EFI from the original ElCap branch. Thus was not able to test the post-install. I had removed all devices which hold my current workable-but-not-perfect Multibeast/Clover Sierra install, and was going to target a clean SSD. but could not get the installer to boot.

After putting in the UEFI bios settings here, I then tried installing Sierra with two different USBs, both created with the "createInstallMedia" approach using an Install OS X Sierra plus the install EFI from here. That would not get through the first boot into the installer. Just for fun, I also tried installing the latest version of Clover (3899 I believe) onto the USB then copying in the kexts, UEFI drivers and config from this site. also tried several different USB ports. All attempts were same result. All would get just to the first black screen/Apple Logo, then get stuck with the beachball and zero on the progress bar.

Really, the is the same experience I had with this toolset last year with ElCap. Exactly the same stall before getting to the installer. Last year, I eventually fiddled with bios settings, and probably config.plist, and eventually got a first install. After that, the post-install worked great, and I had a very solid ElCap. That ElCap did not, however get me to Sierra with straight upgrade from App Store, so I ended up trying Uni/Multibeast, which has sorta worked.

Would love to get this approach to work, but need some tips how to get the initial install to work.

**Comment by mickelsn** [comment]
I haven't been able to test yet - having some other issues on my El Cap install that I need to address first.

That said, you Kay want to try making a Sierra USB by adapting the install instructions on this site for the MASTER branch, just changing the git clone command to reflect the SIERRA branch. That's what I plan to do to see if I can use this for a clean install.

RacerMaster, will that work?

**Comment by theracermaster** [comment]
Yep. Follow the instructions in the README (on the Sierra branch, of course).

**Comment by theracermaster** [comment]
@Bobbm, what's your hardware (in addition to your motherboard of course)?

**Comment by Bobbm** [comment]
- Mobo is UD3H, rev 1.2, BIOS ver FA
- Intel i7, IvyBridge, forgotten speed, its a non-overclockable version
- Display Samsung SyncMaster SB24B150 connected via HDMI (Using internal gfx both during install and thereafter)
- DRAM Kingston DDR3-1600  2X  KHX1600C9D3K2/8GX in slots 1, 3
- CoolerMaster power, 420w
- Seagate Momentus 5400 160GB (this was a spare lying around, used only for this recent install attempt, tho as explained, didn't even get into install to hit it with DiskUtil; my regular OS drives are a Samsung SSD 240GB, plus a Seagate 1T 7800 for data, both disconnected for install attempt. Plan is to clone back to this SSD if I can achieve a stable install onto spare drive with your tools)
- Dell USB Kbd, with wireless mouse by Microsoft connected via kbd’s thru-USB  (this kbd sometimes fails to register during Clover boot, but usually is fine once OS boot starts)

During install attempt everything else is removed/disconnected. In normal use I also have a Roland Quad-Capture Audio/MIDI interface which connects via USB 2.0, so do not normally care about onboard sound. I also have a DVD rec/player connected via SATA, but this is rarely sed and also not connected during install attempt.

**Comment by Bobbm** [comment]
I recently went ahead and tried the Sierra branch script.

Even though I had never been able to get an initial install using the EFI on the main branch here, I couldn't resist my curiosity, so just took a chance and ran the script on a Sierra install I had previously done using other tools. 

The previous install was workable, though some USB ports were erratic and pretty sure other things such as CPU states, etc were sub-optimal. Also, my LAN would only connect to my Gbps switch at 100mbps, not G, though pretty sure that was due more to crap cables/connectors, since same problem with real mac over that particular cable.

Anyway, after running the script and one or two initial failed boots, now it boots fine and most functions I have looked at so far seem working.

Except I have no LAN at all. 

Kextstat does not show AtherosE2200Ethernet.kext as being loaded. I have rebooted "without caches" just to make sure, but still NG.   I checked that AtherosE2200Ethernet.kext is present in EFI/Clover/kexts/other.

Any advice?

**Comment by jbrodriguez** [comment]
@theracermaster,

I just ran your script on my GA-Z77X-UD5H board and it worked beautifully.

Thanks a lot for your work on this !

**Comment by ratio187** [comment]
@jbrodriguez I have the same board and have a few questions:

- What processor do you have?
- What BIOS version are you running
- Is sleep/wake working flawlessly for you?

Thanks!

**Comment by jbrodriguez** [comment]
hi @ratio187 ,


> What processor do you have?
**Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz**

> What BIOS version are you running
**F16g**

> Is sleep/wake working flawlessly for you?
**Sleep works flawlessly. To wake it up I have to press any key twice (the second time to wake up the monitors), but it's absolutely not a big deal to me. I have CODE mechanical keyboard (wired) and a Logitech Performance MX mouse (wireless)**

> iMessage/App Store working fine?
**No issues with the App Store at all.** 

Don't use iMessage nor Handoff.
