### ISSUE TITLE
Fix port issues with Intel USB controllers on 10.11+

### ISSUE THREAD

**Issue by theracermaster** [theracermaster/Gigabyte-GA-Z77X-macOS-Install#35]
The USB stack in 10.11/10.12 has proven to be problematic for some users, even with a port injector. In the [`Sierra` branch](https://github.com/theracermaster/Gigabyte-GA-Z77X-DSDT-Patch/tree/sierra), I have removed the port injector, using Clover kext patches to prevent the default port injectors for iMac13,2 from loading.

If you used the [`Sierra` branch](https://github.com/theracermaster/Gigabyte-GA-Z77X-DSDT-Patch/tree/sierra) and still have USB issues, please reply to this issue with the following information:
- macOS version (newer is better)
- USB device that you tried (with USB version [2.0 or 3.0])
- [IORegistryExplorer](https://github.com/toleda/audio_ALCInjection/blob/master/IORegistryExplorer_v2.1.zip) dump showing hotplugging of the device

Note that this issue only pertains to the Intel EHCI & xHCI controllers on installs using the [`Sierra` branch](https://github.com/theracermaster/Gigabyte-GA-Z77X-DSDT-Patch/tree/sierra). Issues with third-party xHCI controllers for installs using the [`Sierra` branch](https://github.com/theracermaster/Gigabyte-GA-Z77X-DSDT-Patch/tree/sierra) should be addressed in issue #36.

**Comment by mickelsn** [comment]
I'll try to test this as a clean install in a couple days - I'm traveling for work. I have a Z77X UP5 TH motherboard.

**Comment by mickelsn** [comment]
Racer - Question on doing a clean install via USB stick...do I use the OS X Install Files here (https://github.com/theracermaster/Gigabyte-GA-Z77X-OS-X-Install) to bless my USB stick for booting, as instructed in the Master branch wiki, or so I somehow need to use the Sierra branch?

**Comment by theracermaster** [comment]
For now, you should be able to use the OS-X-Install repo files (if they worked for you on 10.11). I need to get around to updating it.

**Comment by theracermaster** [comment]
*Should* be fixed in v2.0.0, will reopen if more issues are reported.
