### ISSUE TITLE
Fix third party xHCI controllers on 10.11+

### ISSUE THREAD

**Issue by theracermaster** [theracermaster/Gigabyte-GA-Z77X-macOS-Install#36]
The USB stack in 10.11/10.12 is not compatible with the [AppleUSBXHCI patches](http://www.insanelymac.com/forum/files/file/150-patched-appleusbxhci/) used on 10.10 and lower. GenericUSBXHCI seems to be unreliable, so I added an injector that fakes the VIA VL800 xHCI controller as the Fresco Logic FL1100 xHCI controller (natively supported by AppleUSBXHCIPCI.kext) in the [`Sierra` branch](https://github.com/theracermaster/Gigabyte-GA-Z77X-DSDT-Patch/tree/sierra). Since I do not have a motherboard with third party xHCI controllers, I am unable to test if this actually works.

If you do have a motherboard with the VIA VL800 xHCI controller, please test with the  [`Sierra` branch](https://github.com/theracermaster/Gigabyte-GA-Z77X-DSDT-Patch/tree/sierra) and reply with results.

**Comment by thokis** [comment]
Unfortunately it does not seem do work. Can I provide you something what could help you with this issue?

**Comment by theracermaster** [comment]
Can you post an IOReg dump and the output of `bdmesg`?

**Comment by CoBrA2168** [comment]
Do you know which motherboards have this USB chipset? I have the Z77X-UD5H, not sure if that has VIA USB or not.

**Comment by theracermaster** [comment]
GA-Z77X-UD5H doesn't have VIA xHC, only Intel.

**Comment by CoBrA2168** [comment]
I'll likely give the Sierra branch a shot soon, which is why I was asking.  I'm still running El Capitan (which I setup completely using your script from the main branch).
