### ISSUE TITLE
Sierra Branch: Potential Issue with Broadcom BCM94360CD for Bluetooth 4.0

### ISSUE THREAD

**Issue by mickelsn** [theracermaster/Gigabyte-GA-Z77X-macOS-Install#40]
Greetings...I'm in the process of testing your Sierra branch as a path to macOS Sierra from an existing installation of El Capitan that used your earlier patch to get everything working. I think I've hit a bug.

I was able to upgrade the EFI deployment mostly successfully (except I forgot to migrate working serial numbers so I caused myself all kinds of iMessage hell, but I know how to fix that), but the system can't seem to find the Bluetooth hardware correctly to activate it. The Wi-Fi is working fine.

Any ideas on how to troubleshoot?

**Comment by theracermaster** [comment]
Can you post an IOReg dump?

**Comment by mickelsn** [comment]
Here you go. Key details:

- Gigabyte Z77X-UP5-TH board
- 3770K processor
- GeForce 650 Ti graphics card
- 32GB RAM
- [Bluetooth/WiFi card from OSXWiFi.com](http://www.osxwifi.com/adapters/apple-wifi-bt-4-0-card-to-pci-e-x1-adapter-for-pc-hackintosh)
- HiPoint RocketRAID card for extra SATA capacity, in JBOD configuration

[Black Slab.ioreg.zip](https://github.com/theracermaster/Gigabyte-GA-Z77X-DSDT-Patch/files/614563/Black.Slab.ioreg.zip)

**Comment by mickelsn** [comment]
For what it's worth - WiFi is working fine. Bluetooth menu bar icon is crossed out, menu item says "Bluetooth: Not Available".

I'll try to boot with my backup of a known good configuration to confirm that I didn't somehow bork the hardware, but that's going to take a bit since I need to back port my new machine serial numbers so I don't screw up iMessage (again)...

**Comment by theracermaster** [comment]
Can you post a dump with IORegistryExplorer v2.1?

**Comment by mickelsn** [comment]
Ask and ye shall receive.

[Black Slab.ioreg.zip](https://github.com/theracermaster/Gigabyte-GA-Z77X-DSDT-Patch/files/614885/Black.Slab.ioreg.zip)

A couple other things I've noticed:

USB ports do not seem to be working correctly. Here are the symptoms:
- Apple Wired Keyboard working in USB2 port on back of motherboard (controls BIOS as well as Chrome boot menu options; works upon boot into OS X 10.11.6)
- Logitech USB wireless mouse working in USB2 port on back of motherboard (also controls BIOS and works upon boot into OS X)
- Broadcom WiFi/Bluetooth card is plugged into F_USB2 header on motherboard. It's visible to System Profiler, but shows as "Composite Device" instead of a Bluetooth receiver. See attached image.
![screen shot 2016-11-27 at 1 26 41 pm](https://cloud.githubusercontent.com/assets/15273114/20650796/2b7f22b4-b4a5-11e6-8a7a-9d93be2e7f18.png)
- It appears that all USB3 ports are dead -- they are visible in System Profiler, but they don't seem to recognize any devices when plugged in. I've tried a hard drive and a USB soundcard, both of which worked fine with previous Patch (v1.8.1) and this hardware.

At this point, I suspect that there's something not working correctly in the USB configuration with your Sierra branch of the patch, at least for the Z77X-UP5 TH motherboard.

I'm going to move my serial numbers over to my other boot drive and make sure I can get the system back the way it was, but will maintain this drive to assist in troubleshooting if needed. Thanks again for your work!

**Comment by mickelsn** [comment]
I've got the system back up and running under the older version of the patch now, and I've used what I learned to track down a lingering bugs in the old setup which really didn't matter much day-to-day...I found the causes of a long-standing issue with my old setup where I couldn't use my keyboard in the BIOS or Clover setup menu. It seems that if I had my USB3 hub plugged into a USB3 bus, the USB2 keyboard was inactive until Mac OS X booted. That now seems fixed as I have disconnected the hub. I don't have another one handy to isolate items to either a bad hub or something else.

Anyway, I've attached an IOReg dump of my system with this working configuration in case it helps you in any way. Again, thanks!
[TowerMac.ioreg.zip](https://github.com/theracermaster/Gigabyte-GA-Z77X-DSDT-Patch/files/615021/TowerMac.ioreg.zip)

**Comment by mickelsn** [comment]
Just checking in - any ideas? Thanks!

**Comment by theracermaster** [comment]
Sorry for not responding - I'm really busy this week and away from my Hack. I'll get back to you whenever possible (hopefully within a few days).

**Comment by mickelsn** [comment]
Cool, no problem! Just wanted to make sure you didn't want any other data files from me to help chase things down yet. Cheers!

**Comment by mickelsn** [comment]
Hey Racer...just checking in to see if you had had a chance to look into the issue. I'm guessing it's a USB thing since that's where the Bluetooth on the board seems to interface with the hardware and judging from other USB behaviors, and unfortunately I have no idea what I'm doing there to help troubleshoot. Thanks again!

**Comment by theracermaster** [comment]
For some reason it looks like the AppleUSBHub isn't getting patched. The kext patch (in config.plist) disables the default USB hub port injector (for iMac13,X); without it, you'll only have a few of your USB ports on EHC1 working (PRT1/3/8). As for XHC, I'm not sure why it isn't working. The ports are visible in your IOReg dump and appear to be working.

**Comment by mickelsn** [comment]
What can I do to help you troubleshoot? I can try to map out which USB ports are working and which aren't (motherboard back panel USB2 and USB3, front panel USB2 and USB3 that are attached to MB headers, as well as the Bluetooth card attached to a USB2 header and some extra USB3 ports I have attached to a header), and give you that information to compare with the IOReg dump...maybe alongside an IOReg dump from the working El Capitan install I have with the current script?

**Comment by theracermaster** [comment]
Can you post a dump of your ACPI tables? I feel like bit 1 of _UPC might not be set to connectable (which will cause macOS to ignore the port).

**Comment by mickelsn** [comment]
Sorry for the long-delayed reply, I've been swamped with the holidays.

Can you tell me the easiest way to dump the tables? I'm a tad bit of an amateur here at this...Perhaps I need to use IOJOnes to dump out the IOACPIPlane? Or do I need to use another tool?

I've got a bit more free time this week and next to try and help with troubleshooting...hopefully we can close this out if it works for you!

Thanks again...

**Comment by theracermaster** [comment]
Are you running the latest UEFI firmware? If so, I can extract the tables from it (without a dump).

**Comment by mickelsn** [comment]
Sorry for the delay. I'm running stock UEFI firmware, I think F11. Will try to check to confirm.

**Comment by mickelsn** [comment]
A quick follow-up after a long delay (sorry) - I am indeed running F11 BIOS (stock on motherboard from purchase).

**Comment by theracermaster** [comment]
Closing this as it's fairly old (based off v1.x.x of the script). Feel free to reopen this if you encounter any similar issues with v2.0.6.
