### ISSUE TITLE
Gigabyte GA-Z77X-UP4 TH Support

### ISSUE THREAD

**Issue by Ninerian** [theracermaster/Gigabyte-GA-Z77X-macOS-Install#44]
Hello, 

just discovered you're repo and I'm quiet impressed by your work. As you requested in the wiki, I request the support of the Gigabyte GA-Z77X-UP4 TH motherboard. A dump from IORegistryExplorer is attached.

[GA-Z77X-UD4 TH.ioreg.zip](https://github.com/theracermaster/Gigabyte-GA-Z77X-DSDT-Patch/files/712270/GA-Z77X-UD4.TH.ioreg.zip)

**Comment by Ninerian** [comment]
Corrected the name of the motherboard.

**Comment by theracermaster** [comment]
Thank you! I'm working on refactoring some parts of the repo right now, and will add this as soon as possible.

**Comment by Ninerian** [comment]
I got El Capitan installed on my PC. I only have some quirks I want to document, to help you with the development. 
I changed your install script to recognize the name of the board. Also I had to change the dsl file, as it didn't compile. Now the system is booting and running. The following misbehaviors I have noticed:
- no network without kext
- no sound
- only the two USB 3.0 ports are working
- while recovering from a time machine backup via the migration manager, the PC reboots at finding the time machine.

I attached the system log of the first boot cycles, so you can get some more information.
[system.log.zip](https://github.com/theracermaster/Gigabyte-GA-Z77X-DSDT-Patch/files/715819/system.log.zip)

**Comment by deweydb** [comment]
+1 would love to see support for this motherboard.

**Comment by deweydb** [comment]
Ok. I found the line that causes problems and commented it out, but i'm not really sure if that is the correct solution.

For other people that find this, in SSDT-GA-Z77X-UP4-TH.dsl

replace:
Scope (GLAN) { Name (_STA, Zero) }
with:
/* Scope (GLAN) { Name (_STA, Zero) } */

**Comment by theracermaster** [comment]
Support has been added in v2.0.2. Please reply with a IOReg dump if possible.
