### ISSUE TITLE
"no such file or directory" during installation

### ISSUE THREAD

**Issue by Philipondio** [theracermaster/Gigabyte-GA-Z77X-macOS-Install#45]
Hi Alex!
Running the script, I get the following errors *no such file or directory* (running 10.12.3):

Generating SMBIOS data:
_genSMBIOSData:12: **no such file or directory**: /Users/xxx/Gigabyte-GA-Z77X-DSDT-Patch/modules/MacGen/simpleMacSerial.sh
_genSMBIOSData:13: **no such file or directory**: /Users/xxx/Gigabyte-GA-Z77X-DSDT-Patch/modules/MacGen/simpleMLBSerial.sh
 - Product Name: iMac13,2
 - Serial Number: 
 - MLB Serial Number: 
 - System UUID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Beside that, everything in the script installs fine.

Is this a problem?
Thanks!

**Comment by Philipondio** [comment]
When I finish the installation and reboot, I can't get into the Clover bootscreen anymore.
Instead, I get this error:

**Reboot and Select proper Boot device
or Insert Boot Media in selected Boot device and press a key**

**Comment by janko84** [comment]
I have the same problem, any suggestion?

**Comment by HypervisorX** [comment]
can you confirm you followed the instructions for setup in github wiki for this project, including the [UEFI configuration](https://github.com/theracermaster/Gigabyte-GA-Z77X-DSDT-Patch/wiki/1.-UEFI-Configuration)?
also what hardware are you using?

**Comment by janko84** [comment]
I have z77x-d3h, i7 3770 and gtx660, I pulled this version: git clone --recursive https://github.com/theracermaster/Gigabyte-GA-Z77X-DSDT-Patch --branch sierra
and than - ./GA-Z77X.sh --install
I already had clover installed and I did your tweak https://github.com/theracermaster/Gigabyte-GA-Z77X-DSDT-Patch/pull/46/commits/602447b4dcb9a206dc8c567826d6e4eedee20cf8, config.plist is fully generated now, but still clover boot manager not working.

**Comment by theracermaster** [comment]
Should be fixed in v2.0.0.

**Comment by janko84** [comment]
Thanks for the update, but I have the new problem now: ./GA-Z77X.sh: line 234: /Users/janko/Gigabyte-GA-Z77X-macOS-Install-master/acpi/tools/mount_efi.sh: No such file or directory - I have tried to mount efi partition manually but without success.

**Comment by theracermaster** [comment]
Make sure that you clone the repo with `git clone --recursive`. `mount_efi.sh` is included in one of the submodules.
