### ISSUE TITLE
Compatibility GA-Z77X-UP4 TH

### ISSUE THREAD

**Issue by MartinMenzel** [theracermaster/Gigabyte-GA-Z77X-macOS-Install#47]
**System information**
 - macOS 10.12.2
 - GA-Z77X macOS Install v2.0.3
 - GA-Z77X-UP4 TH (Bios F9)
 - Intel Core i7-3770K
 - Saphire ATI Radeon HD 5770 1024 MB
 
**Issue description**
 ERROR: Z77X-UP4 is unsupported by this script
[bootlog.log.txt](https://github.com/theracermaster/Gigabyte-GA-Z77X-macOS-Install/files/882291/bootlog.log.txt)

thank you!

**Comment by theracermaster** [comment]
Can you post a IOReg dump as well?

**Comment by MartinMenzel** [comment]
yes!, here my IOReg dump file:
[Martin’s IOReg dump file.zip](https://github.com/theracermaster/Gigabyte-GA-Z77X-macOS-Install/files/883565/Martin.s.IOReg.dump.file.zip)

**Comment by theracermaster** [comment]
This should be fixed with the latest commit. Feel free to reopen if you encounter issues.
