### ISSUE TITLE
Kernel panic after iographics flags 0x43

### ISSUE THREAD

**Issue by nosize** [theracermaster/Gigabyte-GA-Z77X-macOS-Install#48]
**System information**
 - macOS 10.12.4
 - GA-Z77X macOS Install v2.0.4
 - GA-Z77X-UD5H
 - Intel Core i7-3770K
 - NVIDIA GeForce GTX 970

**Issue description**
 - Kernel panic image/log (if applicable): https://i.imgur.com/xxxxxxx.png
 - [x ] I'm trying to boot the macOS installer
 - [x ] I'm trying to boot my macOS install

**Comment by theracermaster** [comment]
Can you post an image of the panic?

**Comment by nosize** [comment]
![vlcsnap-2017-03-31-18h56m37s376](https://cloud.githubusercontent.com/assets/93775/24558449/dd705ede-1643-11e7-825c-e7058c26ce28.png)

**Comment by theracermaster** [comment]
Are you booting your macOS partition or are you booting the installer?

**Comment by nosize** [comment]
mac os partition and installer

**Comment by nosize** [comment]
If you change the value of init display first - igfx in the BIOS, it is possible to boot mac os partition

**Comment by theracermaster** [comment]
When you boot macOS (after the panic), you should get a window asking you to report an error. Click yes and post the full panic log here (put it on Pastebin/etc and link it).

**Comment by nosize** [comment]
Strange, but in this case such a window does not appear

**Comment by nosize** [comment]
Clover boot log [log.txt](https://github.com/theracermaster/Gigabyte-GA-Z77X-macOS-Install/files/886384/log.txt)

**Comment by theracermaster** [comment]
Any panic logs in /Library/Logs/DiagnosticReports?

**Comment by nosize** [comment]
[ioreg.zip](https://github.com/theracermaster/Gigabyte-GA-Z77X-macOS-Install/files/886650/ioreg.zip)

**Comment by nosize** [comment]
[last_diagnostic_report_file_list.txt](https://github.com/theracermaster/Gigabyte-GA-Z77X-macOS-Install/files/886684/last_diagnostic_report_file_list.txt)

**Comment by nosize** [comment]
Change BIOS value Internal Graphics: Auto and all works

**Comment by theracermaster** [comment]
That's strange. What BIOS version are you using?

**Comment by nosize** [comment]
F16h
