### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by nosize** [theracermaster/Gigabyte-GA-Z77X-macOS-Install#50]
**System information**
 - macOS 10.12.4
 - GA-Z77X macOS Install v2.0.5

**Issue description**

tools/mkusb "/Volumes/Install macOS Sierra"
macOS installer ESP mounted at /Volumes/EFI 1.
Installing Clover to /Volumes/EFI 1...cp: /Users/sashka/Gigabyte-GA-Z77X-macOS-Install/tools/../efi/drivers/AptioFix2.efi: No such file or directory

**Comment by osergios** [comment]
I have this problem too ....

**Comment by theracermaster** [comment]
Sorry for the issue, should be fixed with the latest commit.

**Comment by osergios** [comment]
You are awesome !!!
