### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by tarik50** [theracermaster/Gigabyte-GA-Z77X-macOS-Install#59]
Generating SMBIOS data:
 - Product Name: iMac13,2
 - Serial Number: C02JYCSIFP13
 - MLB Serial Number: C02254602NAF64W1M
 - System UUID: 9A3D2002-6C70-4665-ACFC-AFBA0606A46F
cp: /usr/local/bin/bdmesg: Permission denied

**Comment by theracermaster** [comment]
This should be fixed with the latest commit. Feel free to reopen this issue if you encounter any other problems.
