### ISSUE TITLE
Failed to generate SSDT

### ISSUE THREAD

**Issue by tarik50** [theracermaster/Gigabyte-GA-Z77X-macOS-Install#61]
Detected motherboard: Gigabyte GA-Z77X-UD3H
Script arguments: ./GA-Z77X.sh --install: Installing Clover & kexts
--------------------------------------------------------------------------------
Compiling and copying DSDT:
src/panther_point/pci/imei.asl     23: ckage (Zero) {})
Remark   2095 -                          Effective AML package length is zero ^ 

Compilation complete. 0 Errors, 0 Warnings, 1 Remarks, 3 Optimizations
Generating SSDT for Intel Core i5-2500K CPU @ 3.70 GHz (max turbo):

cp: /Users/tarik/Library/ssdtPRGen/ssdt.aml: No such file or directory
iMac:Gigabyte-GA-Z77X-macOS-Install tarik$

**Comment by tarik50** [comment]
cp: /Users/tarik/Library/ssdtPRGen/ssdt.aml: No such file or directory

**Comment by theracermaster** [comment]
Can you post the output of `set -x GA-Z77X.sh --install`?

**Comment by tarik50** [comment]
The command does not work.
bash -x GA-Z77X.sh --install

**Comment by tarik50** [comment]
When the PC started without USB.The apple remains with the bar loading.Do not go there

**Comment by z77xd3h** [comment]
same CPU and same problem here.  and one more problem.
I can boot up from installer EFI  but  get random screen flickering with gt 630  videocard.
it is an old problem. the card works only imac 12.1 smbios.
well,  it used to work. now I  get black screen with 12.1. 
 gt610 works fine your scripts  smbios 13.2

**Comment by z77xd3h** [comment]
bash -x GA-Z77X.sh --install  output:
Compiling and copying DSDT:
+ BOARD=Gigabyte/GA-Z77X-D3H
+ make install -C '/Volumes/Install macOS Sierra/Gigabyte-GA-Z77X-macOS-Install/acpi'
+ tail -n 2
+ head -n 1
src/panther_point/pci/imei.asl     23: ackage (Zero) {})
Remark   2095 -                          Effective AML package length is zero ^ 

Compilation complete. 0 Errors, 0 Warnings, 1 Remarks, 0 Optimizations
++ '/Volumes/Install macOS Sierra/Gigabyte-GA-Z77X-macOS-Install/tools/bdmesg'
++ awk '/Turbo:/ {print $4}'
++ tr / '\n'
++ awk 'NR==1 {max=$1} { if ($1>max) max=$1} END {printf "%d\n", max}'
+ local maxTurboFreq=3700
++ sysctl -n machdep.cpu.brand_string
++ tr -d '(TM)'
++ awk '{print $2, $3}'
+ local 'cpuBrandString=Core i5-2500'
++ bc
+ printf '%bGenerating SSDT for Intel Core i5-2500 CPU @ 3.70 GHz (max turbo)%b:\n' '\e[1m' '\e[0m'
Generating SSDT for Intel Core i5-2500 CPU @ 3.70 GHz (max turbo):
++ yes n
++ '/Volumes/Install macOS Sierra/Gigabyte-GA-Z77X-macOS-Install/tools/ssdtPRGen.sh/ssdtPRGen.sh' -turbo 3700 -x 1
++ tail -n 1
+ echo ''

+ cp /Users/maccom/Library/ssdtPRGen/ssdt.aml /Volumes/EFI/EFI/CLOVER/ACPI/patched/SSDT-PR.aml
cp: /Users/maccom/Library/ssdtPRGen/ssdt.aml: No such file or directory

**Comment by z77xd3h** [comment]
the script worked on 12.3. it did not work on 12.0  and 12.5
I did not try other versions of sierra.

**Comment by theracermaster** [comment]
This should be fixed by v2.0.8 (I removed ssdtPRGen.sh entirely).
