### ISSUE TITLE
Cannot Boot USB Stick on GA-Z77X-UP5-TH

### ISSUE THREAD

**Issue by mickelsn** [theracermaster/Gigabyte-GA-Z77X-macOS-Install#64]
**System information**
 - macOS 10.12.x (Installer)
 - GA-Z77X macOS Install v2.0.7 (just made today)
 - GA-Z77X-UP5-TH
 - Intel Core i7-3770K
 - NVIDIA GeForce GTX 650 Ti (both installed and not installed)

**Issue description**
 - Kernel panic image/log (if applicable): http://imgur.com/a/kOHRo
 - [X] I'm trying to boot the macOS installer
 - [ ] I'm trying to boot my macOS install
 - [ ] I can boot my macOS install, but it has problems
 - [ ] Can you add support for my board?

PROBLEM - I can't boot into the installer on a fresh USB stick.

I created a new USB stick with no problems - latest version of Sierra as well as v2.0.7 of your script as of today.

All drives disconnected from motherboard except 1TB SSD (for install destination) and USB stick for installer (plugged in USB port on rear of motherboard). Removed all PCIe cards except a combo AirPort/Bluetooth card from OSXwifi (works pretty much fine under El Capitan and prior).

Boot sequence starts fine - video is all good, both on GT 650 Ti and Intel graphics. But verbose boot log shows the system hanging somewhere in the USB / HID sequence. See linked graphics for details.

Any ideas on what's going wrong? My El Capitan system is working with prior (v1.0.x) version of your script.

**Comment by theracermaster** [comment]
I can't seem to open that imgur link. Can you post another link for the verbose boot log?

**Comment by mickelsn** [comment]
Crap - sorry, try this one:

http://imgur.com/a/awV5a

I tried getting verbose boot log, but it doesn't appear to have been saved anywhere to the USB stick that I could find...where would that be if it saved?

**Comment by theracermaster** [comment]
By verbose boot log I was referring to the images (it won't be autosaved to the USB). As for this issue, I can reproduce it (`Still waiting for root device` means that USB isn't working properly), so I will do some more testing and see what I need to fix.

**Comment by mickelsn** [comment]
Cool - thanks!

**Comment by mickelsn** [comment]
One question out of curiosity - should I ensure I'm installing from a USB2 slot, perhaps with USB2 flash drive? I'm using a USB3 drive currently, and I believe it was in a USB3 slot...

**Comment by mickelsn** [comment]
Hey, racer, just checking in - any luck on updates to try and fix? Thanks in advance!!

**Comment by theracermaster** [comment]
Hey, sorry for not responding (was really busy with real life stuff). I've been pushing commits to some of the related repos (MacGen, hack-acpi) but haven't gotten around to fixing this yet. I'll push a fix soon.

**Comment by mickelsn** [comment]
Understand the real life then completely! This might work out great, because I think I'm going to have some time to play with my machine this weekend.

As always, thanks for all you do with this.

**Comment by theracermaster** [comment]
Sorry for taking so long, but v2.0.8 should've fixed it. Please feel free to reopen this if you continue to encounter this issue.
