### ISSUE TITLE
any plan to add in support to have 'update' to the kexts only?

### ISSUE THREAD

**Issue by johnnykang** [theracermaster/Gigabyte-GA-Z77X-macOS-Install#8]
Not really an issue or defect, but i just wonder if you have any plan to have partial option to only update the kexts (esp. the USB part on 10.11)without reinstalling Clover, or anything else that is not related to the kexts?

If you don't have any plan, I will fork this project and add those in there.  It can be useful when Apple releases new update and breaks the existing 'custom' kexts (for example the USB kexts on 10.11).

**Comment by theracermaster** [comment]
This seems like a good idea, but unfortunately I am extremely busy at the moment; I should have some more time over the weekend to try to implement this. Thanks for the suggestion.
